import uuid
from datetime import datetime
from decimal import Decimal
from sqlalchemy import String, Text, Enum, ForeignKey, Boolean, Integer, Numeric, DateTime, Index, UniqueConstraint, JSON
from sqlalchemy.dialects.postgresql import UUID, JSONB
from sqlalchemy.orm import Mapped, mapped_column, relationship
from app.core.database import Base
from app.models.mixins import UUIDPrimaryKeyMixin, TimestampMixin
from app.models.enums import *
E=lambda cls: Enum(cls, values_callable=lambda e:[x.value for x in e])
class Profile(Base, TimestampMixin):
    __tablename__='profiles'; id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True), primary_key=True); email:Mapped[str]=mapped_column(String(320), unique=True, index=True); full_name:Mapped[str|None]=mapped_column(String(160)); role:Mapped[ProfileRole]=mapped_column(E(ProfileRole), default=ProfileRole.BUSINESS_OWNER); memberships=relationship('BusinessMember', back_populates='user')
class Business(Base, UUIDPrimaryKeyMixin, TimestampMixin):
    __tablename__='businesses'; name:Mapped[str]=mapped_column(String(180)); slug:Mapped[str]=mapped_column(String(220), unique=True, index=True); industry:Mapped[str|None]=mapped_column(String(120)); phone:Mapped[str|None]=mapped_column(String(60)); contact_email:Mapped[str|None]=mapped_column(String(320)); address:Mapped[str|None]=mapped_column(String(320)); logo_url:Mapped[str|None]=mapped_column(String(600)); brand_color:Mapped[str]=mapped_column(String(20), default='#2563EB'); status:Mapped[BusinessStatus]=mapped_column(E(BusinessStatus), default=BusinessStatus.PENDING, index=True); smart_auto_reply:Mapped[bool]=mapped_column(Boolean, default=False); owner_approval_required:Mapped[bool]=mapped_column(Boolean, default=True); created_by:Mapped[uuid.UUID|None]=mapped_column(UUID(as_uuid=True)); members=relationship('BusinessMember', back_populates='business'); forms=relationship('Form', back_populates='business'); leads=relationship('Lead', back_populates='business')
class BusinessMember(Base, UUIDPrimaryKeyMixin, TimestampMixin):
    __tablename__='business_members'; __table_args__=(UniqueConstraint('business_id','user_id',name='uq_business_members_business_user'), Index('ix_business_members_user_business','user_id','business_id')); business_id:Mapped[uuid.UUID]=mapped_column(ForeignKey('businesses.id',ondelete='CASCADE')); user_id:Mapped[uuid.UUID]=mapped_column(ForeignKey('profiles.id',ondelete='CASCADE')); role:Mapped[MemberRole]=mapped_column(E(MemberRole), default=MemberRole.OWNER); is_active:Mapped[bool]=mapped_column(default=True); business=relationship('Business', back_populates='members'); user=relationship('Profile', back_populates='memberships')
class Form(Base, UUIDPrimaryKeyMixin, TimestampMixin):
    __tablename__='forms'; __table_args__=(Index('ix_forms_business_slug','business_id','slug'),); business_id:Mapped[uuid.UUID]=mapped_column(ForeignKey('businesses.id',ondelete='CASCADE')); slug:Mapped[str]=mapped_column(String(220), unique=True, index=True); title:Mapped[str]=mapped_column(String(180), default='Request a Quote'); description:Mapped[str|None]=mapped_column(String(600)); success_message:Mapped[str]=mapped_column(String(600), default='Thanks. Your request has been received.'); services:Mapped[list|None]=mapped_column(JSONB); is_active:Mapped[bool]=mapped_column(Boolean, default=True); business=relationship('Business', back_populates='forms')
class Lead(Base, UUIDPrimaryKeyMixin, TimestampMixin):
    __tablename__='leads'; __table_args__=(Index('ix_leads_business_status_created','business_id','status','created_at'),); business_id:Mapped[uuid.UUID]=mapped_column(ForeignKey('businesses.id',ondelete='CASCADE')); form_id:Mapped[uuid.UUID|None]=mapped_column(ForeignKey('forms.id',ondelete='SET NULL')); customer_name:Mapped[str]=mapped_column(String(160)); customer_email:Mapped[str|None]=mapped_column(String(320)); customer_phone:Mapped[str|None]=mapped_column(String(80)); service_needed:Mapped[str|None]=mapped_column(String(180)); preferred_time:Mapped[str|None]=mapped_column(String(180)); message:Mapped[str|None]=mapped_column(Text); source:Mapped[str]=mapped_column(String(80), default='public_form'); status:Mapped[LeadStatus]=mapped_column(E(LeadStatus), default=LeadStatus.NEW); estimated_value:Mapped[Decimal|None]=mapped_column(Numeric(10,2)); custom_fields:Mapped[dict|None]=mapped_column(JSONB); business=relationship('Business', back_populates='leads')
class Message(Base, UUIDPrimaryKeyMixin, TimestampMixin):
    __tablename__='messages'; business_id:Mapped[uuid.UUID]=mapped_column(ForeignKey('businesses.id',ondelete='CASCADE')); lead_id:Mapped[uuid.UUID]=mapped_column(ForeignKey('leads.id',ondelete='CASCADE')); direction:Mapped[MessageDirection]=mapped_column(E(MessageDirection)); channel:Mapped[MessageChannel]=mapped_column(E(MessageChannel), default=MessageChannel.EMAIL); message_type:Mapped[MessageType]=mapped_column(E(MessageType), default=MessageType.CUSTOMER_MESSAGE); subject:Mapped[str|None]=mapped_column(String(240)); content:Mapped[str]=mapped_column(Text); external_id:Mapped[str|None]=mapped_column(String(240))
class FollowUp(Base, UUIDPrimaryKeyMixin, TimestampMixin):
    __tablename__='follow_ups'; business_id:Mapped[uuid.UUID]=mapped_column(ForeignKey('businesses.id',ondelete='CASCADE')); lead_id:Mapped[uuid.UUID]=mapped_column(ForeignKey('leads.id',ondelete='CASCADE')); scheduled_at:Mapped[datetime]=mapped_column(DateTime(timezone=True)); status:Mapped[FollowUpStatus]=mapped_column(E(FollowUpStatus), default=FollowUpStatus.SCHEDULED); subject:Mapped[str|None]=mapped_column(String(240)); content:Mapped[str|None]=mapped_column(Text); sent_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True))
class EmailEvent(Base, UUIDPrimaryKeyMixin, TimestampMixin):
    __tablename__='email_events'; business_id:Mapped[uuid.UUID|None]=mapped_column(ForeignKey('businesses.id',ondelete='SET NULL')); lead_id:Mapped[uuid.UUID|None]=mapped_column(ForeignKey('leads.id',ondelete='SET NULL')); to_email:Mapped[str]=mapped_column(String(320)); from_email:Mapped[str]=mapped_column(String(320)); subject:Mapped[str]=mapped_column(String(240)); provider:Mapped[str]=mapped_column(String(80), default='resend'); provider_message_id:Mapped[str|None]=mapped_column(String(240)); status:Mapped[EmailStatus]=mapped_column(E(EmailStatus), default=EmailStatus.QUEUED); error_message:Mapped[str|None]=mapped_column(Text); metadata_json:Mapped[dict|None]=mapped_column(JSONB)
class AIOutput(Base, UUIDPrimaryKeyMixin, TimestampMixin):
    __tablename__='ai_outputs'; business_id:Mapped[uuid.UUID|None]=mapped_column(ForeignKey('businesses.id',ondelete='CASCADE')); lead_id:Mapped[uuid.UUID|None]=mapped_column(ForeignKey('leads.id',ondelete='CASCADE')); output_type:Mapped[AIOutputType]=mapped_column(E(AIOutputType)); model:Mapped[str]=mapped_column(String(120)); prompt_version:Mapped[str]=mapped_column(String(80), default='v1'); raw_output:Mapped[str|None]=mapped_column(Text); structured_output:Mapped[dict|None]=mapped_column(JSONB)
class AuditLog(Base, UUIDPrimaryKeyMixin, TimestampMixin):
    __tablename__='audit_logs'; actor_user_id:Mapped[uuid.UUID|None]=mapped_column(ForeignKey('profiles.id',ondelete='SET NULL')); business_id:Mapped[uuid.UUID|None]=mapped_column(ForeignKey('businesses.id',ondelete='SET NULL')); action:Mapped[str]=mapped_column(String(120)); entity_type:Mapped[str|None]=mapped_column(String(120)); entity_id:Mapped[str|None]=mapped_column(String(120)); details:Mapped[dict|None]=mapped_column(JSONB)
